"""
~~~ DO NOT EDIT, this file is autogenerated by `regarding` ~~~
https://github.com/nicfit/regarding
"""
import dataclasses


@dataclasses.dataclass
class Version:
    major: int
    minor: int
    maint: int
    release: str
    release_name: str


project_name = "regarding"
version = "0.1.1"
release_name = ""
author = "Travis Shirk"
author_email = "travis@pobox.com"
years = ""
version_info = Version(
    0, 1, 1,
    "final", ""
)
description = "Create __about__.py files from `pyproject.toml`."
homepage = "https://github.com/nicfit/regarding"
