
"""
~~~~~~~~~~ DO NOT EDIT THIS FILE! Autogenerated by `regarding` ~~~~~~~~~~
https://github.com/nicfit/regarding
"""
import dataclasses
from typing import Optional

__all__ = ["Version", "project_name", "version", "version_info", "release_name",
           "author", "author_email", "years", "description", "homepage"]


@dataclasses.dataclass
class Version:
    major: int
    minor: int
    maint: int
    release: str
    post: Optional[int]
    dev: Optional[int]
    release_name: Optional[str]


project_name = "regarding"
version = "0.1.5a0"
release_name = ""
author = "Travis Shirk"
author_email = "travis@pobox.com"
years = "2020"
version_info = Version(
    0, 1, 5,
    "a0",
    None, None,
    "",
)
description = "Create __about__.py files for Poetry and setup.py projects."
homepage = "https://github.com/nicfit/regarding"

