
ABOUT_TEMPLATE =\
"""
\"\"\"
~~~~~~~~~~ DO NOT EDIT THIS FILE! Autogenerated by `{regarding_name}` ~~~~~~~~~~
{regarding_homepage}
\"\"\"
import dataclasses
from typing import Optional

__all__ = ["Version", "project_name", "version", "version_info", "release_name",
           "author", "author_email", "years", "description", "homepage"]


@dataclasses.dataclass
class Version:
    major: int
    minor: int
    maint: int
    release: str
    post: Optional[int]
    dev: Optional[int]
    release_name: Optional[str]


project_name = "{project.name}"
version = "{project.version}"
release_name = "{project.release_name}"
author = "{project.author}"
author_email = "{project.author_email}"
years = "{project.years}"
version_info = Version(
    {project.version_info.major}, {project.version_info.minor}, {project.version_info.maint},
    "{project.version_info.release}",
    {project.version_info.post}, {project.version_info.dev},
    "{project.release_name}",
)
description = "{project.description}"
homepage = "{project.homepage}"
"""

from typing import Optional

class Foo:
    x: Optional[int]