[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "regarding"
version = "0.3.0"
description = "Create __about__.py files for Python project metadata."
authors = [
    {name = "Travis Shirk",email = "travis@pobox.com"},
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "toml",
    "packaging",
]

[project.urls]
homepage = "https://github.com/nicfit/regarding"
#
#[tool.poetry.scripts]
#regarding = "regarding.__main__:main"
#
#[tool.poetry]
#include = [
#    "AUTHORS", "Makefile", "tox.ini", "poetry.lock", "requirements.txt",
#    "tests/*.py"
#]
#
#[tool.poetry.group.dev]
#optional = true
#
#[tool.poetry.group.dev.dependencies]
#pytest = "^8.3.4"
#dephell = "^0.8.3"
#tox = "^4.24.1"
#twine = "^6.1.0"
#check-manifest = "^0.50"
#flake8 = "^7.1.2"

[tool.regarding]
years = "2020,2025"
release_name = ""

#[tool.poetry.requires-plugins]
#poetry-plugin-export = ">=1.8"

#[tool.dephell]
#[tool.dephell.main]
#from = {format = "poetry", path = "pyproject.toml"}
#to = {format = "setuppy", path = "setup.py"}
[tool.pdm]
distribution = true
