
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='regarding',
    version='0.1.4-alpha.0',
    description='Create __about__.py files for Poetry and setup.py projects.',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "https://github.com/nicfit/regarding"},
    author='Travis Shirk',
    author_email='travis@pobox.com',
    entry_points={"console_scripts": ["regarding = regarding.__main__:main"]},
    packages=['regarding'],
    package_dir={"": "."},
    package_data={},
    install_requires=['setuptools==50.*,>=50.3.2', 'toml==0.*,>=0.10.2'],
    extras_require={"dev": ["check-manifest==0.*,>=0.45.0", "dephell==0.*,>=0.8.3",
                            "flake8==3.*,>=3.8.4", "pytest==5.*,>=5.2.0", "tox==3.*,>=3.20.1", "twine==3.*,>=3.2.0"]},
)
